# coding: utf-8

# flake8: noqa
"""
    42videobricks

    42videobricks is a Video Platform As A Service (VPaaS)

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.data_video_usage import DataVideoUsage
from openapi_client.models.data_video_usage_list import DataVideoUsageList
from openapi_client.models.error import Error
from openapi_client.models.pagination import Pagination
from openapi_client.models.video import Video
from openapi_client.models.video_assets import VideoAssets
from openapi_client.models.video_attachment import VideoAttachment
from openapi_client.models.video_attachment_list import VideoAttachmentList
from openapi_client.models.video_list import VideoList
from openapi_client.models.video_multipart_upload_finalize import VideoMultipartUploadFinalize
from openapi_client.models.video_multipart_upload_finalize_parts_inner import VideoMultipartUploadFinalizePartsInner
from openapi_client.models.video_multipart_upload_init import VideoMultipartUploadInit
from openapi_client.models.video_multipart_upload_init_response import VideoMultipartUploadInitResponse
from openapi_client.models.video_multipart_upload_init_response_parts_inner import VideoMultipartUploadInitResponsePartsInner
from openapi_client.models.video_properties import VideoProperties
from openapi_client.models.video_upload_init_response import VideoUploadInitResponse
from openapi_client.models.webhook import Webhook
from openapi_client.models.webhook_list import WebhookList
from openapi_client.models.webhook_properties import WebhookProperties
