# coding: utf-8

# flake8: noqa
"""
    42videobricks

    42videobricks is a Video Platform As A Service (VPaaS)

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from 42videobricks-python-client.models.data_video_usage import DataVideoUsage
from 42videobricks-python-client.models.data_video_usage_list import DataVideoUsageList
from 42videobricks-python-client.models.error import Error
from 42videobricks-python-client.models.pagination import Pagination
from 42videobricks-python-client.models.video import Video
from 42videobricks-python-client.models.video_assets import VideoAssets
from 42videobricks-python-client.models.video_attachment import VideoAttachment
from 42videobricks-python-client.models.video_attachment_list import VideoAttachmentList
from 42videobricks-python-client.models.video_list import VideoList
from 42videobricks-python-client.models.video_multipart_upload_finalize import VideoMultipartUploadFinalize
from 42videobricks-python-client.models.video_multipart_upload_finalize_parts_inner import VideoMultipartUploadFinalizePartsInner
from 42videobricks-python-client.models.video_multipart_upload_init import VideoMultipartUploadInit
from 42videobricks-python-client.models.video_multipart_upload_init_response import VideoMultipartUploadInitResponse
from 42videobricks-python-client.models.video_multipart_upload_init_response_parts_inner import VideoMultipartUploadInitResponsePartsInner
from 42videobricks-python-client.models.video_properties import VideoProperties
from 42videobricks-python-client.models.video_upload_init_response import VideoUploadInitResponse
from 42videobricks-python-client.models.webhook import Webhook
from 42videobricks-python-client.models.webhook_list import WebhookList
from 42videobricks-python-client.models.webhook_properties import WebhookProperties
