# coding: utf-8

# flake8: noqa

"""
    42videobricks

    42videobricks is a Video Platform As A Service (VPaaS)

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from 42videobricks-python-client.api.data_api import DataApi
from 42videobricks-python-client.api.tags_api import TagsApi
from 42videobricks-python-client.api.videos_api import VideosApi
from 42videobricks-python-client.api.webhooks_api import WebhooksApi

# import ApiClient
from 42videobricks-python-client.api_response import ApiResponse
from 42videobricks-python-client.api_client import ApiClient
from 42videobricks-python-client.configuration import Configuration
from 42videobricks-python-client.exceptions import OpenApiException
from 42videobricks-python-client.exceptions import ApiTypeError
from 42videobricks-python-client.exceptions import ApiValueError
from 42videobricks-python-client.exceptions import ApiKeyError
from 42videobricks-python-client.exceptions import ApiAttributeError
from 42videobricks-python-client.exceptions import ApiException

# import models into sdk package
from 42videobricks-python-client.models.data_video_usage import DataVideoUsage
from 42videobricks-python-client.models.data_video_usage_list import DataVideoUsageList
from 42videobricks-python-client.models.error import Error
from 42videobricks-python-client.models.pagination import Pagination
from 42videobricks-python-client.models.tag_list import TagList
from 42videobricks-python-client.models.video import Video
from 42videobricks-python-client.models.video_assets import VideoAssets
from 42videobricks-python-client.models.video_attachment import VideoAttachment
from 42videobricks-python-client.models.video_attachment_list import VideoAttachmentList
from 42videobricks-python-client.models.video_list import VideoList
from 42videobricks-python-client.models.video_multipart_upload_finalize import VideoMultipartUploadFinalize
from 42videobricks-python-client.models.video_multipart_upload_finalize_parts_inner import VideoMultipartUploadFinalizePartsInner
from 42videobricks-python-client.models.video_multipart_upload_init import VideoMultipartUploadInit
from 42videobricks-python-client.models.video_multipart_upload_init_response import VideoMultipartUploadInitResponse
from 42videobricks-python-client.models.video_multipart_upload_init_response_parts_inner import VideoMultipartUploadInitResponsePartsInner
from 42videobricks-python-client.models.video_properties import VideoProperties
from 42videobricks-python-client.models.video_upload_init_response import VideoUploadInitResponse
from 42videobricks-python-client.models.webhook import Webhook
from 42videobricks-python-client.models.webhook_list import WebhookList
from 42videobricks-python-client.models.webhook_properties import WebhookProperties
